name: Deploy to Shakedude.com

on:
  push:
    branches: [ main ]  # mainブランチにプッシュされたときに実行

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Create .env file from secrets
      run: |
        echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" > .env
        echo "NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}" >> .env
        echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
        echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
        echo "XAI_API_KEY=${{ secrets.XAI_API_KEY }}" >> .env
        echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> .env
      
    - name: Build project
      run: npm run build
      env:
        # 環境変数を設定
        NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
        NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        
    # 必要なファイルだけをデプロイディレクトリにコピーする
    - name: Prepare deployment files
      run: |
        mkdir -p deploy
        cp -r .next deploy/
        cp -r public deploy/
        cp package.json deploy/
        cp package-lock.json deploy/
        cp next.config.js deploy/
        cp .env deploy/.env
          
    - name: Deploy to Shakedude.com via FTPS
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ftp.3385b51a75b81a95.main.jp
        username: main.jp-3385b51a75b81a95
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        port: 990
        local-dir: ./deploy/
        server-dir: /home/users/3385b51a75b81a95/web/
        dangerous-clean-slate: true
