# これは唯一の公式デプロイワークフローファイルです
# 複数のデプロイを防ぐために、他のデプロイワークフローファイルはすべて削除されています
# このワークフローは、メインブランチへのプッシュ時に自動的に実行されます

name: Deploy to Shakedude.com via SSH

on:
  push:
    branches: [main] # mainブランチにプッシュされたときに実行
    paths-ignore:
      - ".github/workflows/**" # ワークフロー自体の変更ではデプロイしない
      - "README.md"
      - "DEPLOY.md"
      - "docs/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true # 新しいコミットが来たら実行中のワークフローをキャンセル
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Create .env file from secrets
        run: |
          echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" > .env
          echo "NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}" >> .env
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "XAI_API_KEY=${{ secrets.XAI_API_KEY }}" >> .env
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> .env

      - name: Build project
        run: npm run build
        env:
          # 環境変数を設定
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      # 必要なファイルだけをデプロイディレクトリにコピーする
      - name: Prepare deployment files
        run: |
          mkdir -p deploy
          cp -r .next deploy/
          cp -r public deploy/
          cp package.json deploy/
          cp package-lock.json deploy/
          cp next.config.js deploy/
          cp .env deploy/.env

      - name: Deploy files to Shakedude.com (SSH+SFTP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "deploy/**"
          target: "${{ secrets.SSH_DEPLOY_PATH }}"
          rm: true # 既存ファイルを削除してから転送
