name: Deploy to Render

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_VERSION: '20'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci --ignore-scripts
    
    - name: Generate Prisma Client
      run: npx prisma generate
    
    - name: Run linting
      run: npm run lint
      continue-on-error: true
    
    - name: Run tests
      run: npm test
      continue-on-error: true
    
    - name: Build application
      run: npm run build
      env:
        NODE_ENV: production

  deploy:
    name: Deploy to Render
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Trigger Render Deploy
      run: |
        response=$(curl -s -w "%{http_code}" -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}")
        http_code=${response: -3}
        
        if [ $http_code -eq 200 ]; then
          echo "✅ Deploy triggered successfully"
        else
          echo "❌ Deploy failed with HTTP code: $http_code"
          exit 1
        fi
    
    - name: Deployment Notification
      run: |
        echo "🚀 Deployment initiated!"
        echo "Monitor progress: https://dashboard.render.com"
        echo "Live URL: https://your-app.onrender.com"
