# これは唯一の公式デプロイワークフローファイルです
# 複数のデプロイを防ぐために、他のデプロイワークフローファイルはすべて削除されています
# このワークフローは、メインブランチへのプッシュ時に自動的に実行されます

name: Deploy to Shakedude.com via SSH

on:
  push:
    branches: [main] # mainブランチにプッシュされたときに実行
    paths-ignore:
      - ".github/workflows/**" # ワークフロー自体の変更ではデプロイしない
      - "README.md"
      - "DEPLOY.md"
      - "docs/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true # 新しいコミットが来たら実行中のワークフローをキャンセル
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Create .env file from secrets
        run: |
          echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" > .env
          echo "NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}" >> .env
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "XAI_API_KEY=${{ secrets.XAI_API_KEY }}" >> .env
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> .env

      - name: Build project
        run: npm run build
        env:
          # 環境変数を設定
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      # 必要なファイルをそのまま転送（/deploy/サブディレクトリなし）
      - name: List files before deployment
        run: |
          echo "Listing .next directory:"
          ls -la .next || echo ".next directory not found"
          echo "Listing public directory:"
          ls -la public || echo "public directory not found"
          echo "Listing root files:"
          ls -la *.js *.json .htaccess .env start-server.sh LOLIPOP-NODEJS.md || echo "Some files not found"

      - name: Deploy files to Shakedude.com (SSH+SFTP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: ".next/**,.next,.env,server.js,ecosystem.config.js,.htaccess,start-server.sh,LOLIPOP-NODEJS.md,package.json,package-lock.json,next.config.js,public/**,public"
          target: "${{ secrets.SSH_DEPLOY_PATH }}"
          rm: true # 既存ファイルを削除してから転送
          strip_components: 0
          overwrite: true
          debug: true
          
      # サーバー上でPM2を使用してアプリケーションを再起動
      - name: Restart application on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.SSH_DEPLOY_PATH }}
            
            # シェルスクリプトに実行権限を付与
            chmod +x start-server.sh
            
            # 環境情報を出力
            echo "Current directory: $(pwd)"
            echo "Files in directory:"
            ls -la
            
            # ノード環境の確認
            echo "Node.js/npm paths:"
            which node || echo "node not found in PATH"
            which npm || echo "npm not found in PATH"
            
            # 起動スクリプトを実行
            echo "Running start script..."
            ./start-server.sh || bash start-server.sh
            
            echo "Server start attempt completed"

      # フォールバック: SSHを使用して直接ファイルを転送する方法も追加
      - name: Alternative file transfer via SSH (if SCP fails)
        if: failure() # 前のステップが失敗した場合に実行
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # 一時ディレクトリをクリーンアップ
            mkdir -p ${{ secrets.SSH_DEPLOY_PATH }}_tmp
            
            # 削除前に対象ディレクトリが存在するか確認
            if [ -d "${{ secrets.SSH_DEPLOY_PATH }}" ]; then
              echo "Target directory exists, preparing for update"
            else
              echo "Creating target directory"
              mkdir -p ${{ secrets.SSH_DEPLOY_PATH }}
            fi
