name: Deploy to Lolipop

on:
  push:
    branches:
      - master   
      - main  # mainブランチも追加
  workflow_dispatch: # 手動実行も可能

# GitHub Pagesのデプロイを無効にする設定
env:
  PAGES_DEPLOYMENT_DISABLED: true

jobs:
  optimize-and-deploy:
    name: Optimize and FTP Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Create .env file from secrets
        run: |
          echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" > .env
          echo "NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}" >> .env
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "XAI_API_KEY=${{ secrets.XAI_API_KEY }}" >> .env
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> .env

      - name: Build project
        run: npm run build
        env:
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: List files before deployment
        run: |
          echo "Listing .next directory:"
          ls -la .next || echo ".next directory not found"
          echo "Listing .next/server directory:"
          ls -la .next/server || echo ".next/server directory not found"
          echo "Listing public directory:"
          ls -la public || echo "public directory not found"
          echo "Listing root files:"
          ls -la *.js *.json .htaccess .env start-server.sh || echo "Some files not found"
          echo "Build output size:"
          du -sh .next/ || echo "Could not check .next size"

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0  
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_REMOTE_ROOT }}
          local-dir: ./
          exclude: |
            **/.git*/**
            **/node_modules/**
            **/.github/**
            **/backup/**
            **/docs/**
            **/scripts/**
            **/prisma/**
            **/test-config.*
            **/README.md
            **/DEPLOY*.md
