name: SFTP Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build (Next.js)
        run: |
          npm install
          npm run build

      - name: SFTP Deploy
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ssh.lolipop.jp
          username: main.jp-3385b51a75b81a95
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 2222
          source: ".next/**,public/**,package.json,*.js"
          target: "/home/main.jp-3385b51a75b81a95/www"
